### ISSUE TITLE
Explanations Regarding Vivid Talking Head Video Generation

### ISSUE THREAD

**Issue by 2019csz0004** [vico-dataset/vico-dataset.github.io#1]
Dear Authors,

Greetings of the Day!!

Just came across the MM'22 challenge list and found this amazing Conversational Head Generation Challenge. Immediately after reading this challenge, I downloaded the reference paper and started to explore. Responsive Listening Head Video Generation part is pretty clear to me, but I am finding issues with the Vivid Talking Head Video Generation part. Please share some detailed explanations regarding this task along with the baseline papers. 

Thanks and Regards
Gulshan Sharma
email: gulshan.19csz0004@iitrpr.ac.in

**Comment by dc3ea9f** [comment]
Our goal is to provide a concise approach rather than a fancy/complex framework. So, compare to the Responsive Listening Head Video Generation, the baseline for Vivid Talking Head Video Generation just remove the video input (speaker video encoder of Figure 4 in paper) and use bi-lstm for encoding audio features. You can also check the code difference ([speaker generator](https://github.com/dc3ea9f/vico_challenge_baseline/blob/main/vico/networks/speaker_generator.py) vs. [listener generator](https://github.com/dc3ea9f/vico_challenge_baseline/blob/main/vico/networks/listener_generator.py))
